/*
 *  Copyright (c) 2005, Daniel C. Newman <dan.newman@mtbaldy.us>
 *  All rights reserved.
 *  
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *  
 *   + Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *  
 *   + Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *  
 *   + Neither the name of mtbaldy.us nor the names of its contributors
 *     may be used to endorse or promote products derived from this
 *     software without specific prior written permission.
 *  
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 *  OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 *  AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 *  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 *  OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 *  SUCH DAMAGE.
 */
#if !defined(__OWIRE_DEVICES_PRIVATE__)

#define __OWIRE_DEVICES_PRIVATE__

#if defined(__cplusplus)
extern "C" {
#endif

static const char *owire_devices[256] = {
	/* 0x00 */  "Unknown family code 0x00",
	/* 0x01 */  "1-Wire net address / serial number",
	/* 0x02 */  "Multikey, 1152 bit secure memory",
	/* 0x03 */  "Unknown family code 0x03",
	/* 0x04 */  "4K NVRAM, clock, timer, and alarms",
	/* 0x05 */  "Single addressable switch",
	/* 0x06 */  "4K NVRAM iButton",
	/* 0x07 */  "Unknown family code 0x07",
	/* 0x08 */  "1K NVRAM iButton",
	/* 0x09 */  "1K EPROM memory",
	/* 0x0a */  "16K NVRAM iButton",
	/* 0x0b */  "16K EPROM memory",
	/* 0x0c */  "64K to 256K NVRAM iButton",
	/* 0x0d */  "Unknown family code 0x0d",
	/* 0x0e */  "Unknown family code 0x0e",
	/* 0x0f */  "64K EPROM memory",
	/* 0x10 */  "Temperature with alarm trips",
	/* 0x11 */  "Unknown family code 0x11",
	/* 0x12 */  "Dual addressable switch with 1K EPROM memory",
	/* 0x13 */  "Unknown family code 0x13",
	/* 0x14 */  "256 bit EEPROM with 64 bit OTP register",
	/* 0x15 */  "Unknown family code 0x15",
	/* 0x16 */  "Unknown family code 0x16",
	/* 0x17 */  "Unknown family code 0x17",
	/* 0x18 */  "4K NVRAM with SHA-1 engine",
	/* 0x19 */  "Unknown family code 0x19",
	/* 0x1a */  "4K NVRAM with write cycle counters",
	/* 0x1b */  "Battery id with monitor",
	/* 0x1c */  "4K EEPROM with PIO",
	/* 0x1d */  "4K NVRAM with external counters",
	/* 0x1e */  "Unknown family code 0x1e",
	/* 0x1f */  "Two channel addressable coupler for subnetting (Microlan)",
	/* 0x20 */  "4 channel A/D converter",
	/* 0x21 */  "Thermocron temperature logger",
	/* 0x22 */  "Econotemperature",
	/* 0x23 */  "4K EEPROM memory",
	/* 0x24 */  "Real-time clock (RTC)",
	/* 0x25 */  "Unknown family code 0x25",
	/* 0x26 */  "Temperature, A/D (battery monitor)",
	/* 0x27 */  "Real-time clock with interrupt",
	/* 0x28 */  "Adjustable resolution thermometer",
	/* 0x29 */  "8 channel addressable switch",
	/* 0x2a */  "Unknown family code 0x2a",
	/* 0x2b */  "Unknown family code 0x2b",
	/* 0x2c */  "Single channel digital potentiometer",
	/* 0x2d */  "1K EEPROM",
	/* 0x2e */  "Temperature, A/D (battery monitor, charge controller)",
	/* 0x2f */  "1K EEPROM with SHA-1",
	/* 0x30 */  "Temperature, current, A/D (Li+ battery monitor)",
	/* 0x31 */  "Addressable single-cell rechargeable Li+ protection",
	/* 0x32 */  "Unknown family code 0x32",
	/* 0x33 */  "1K EEPROM memory with SHA-1 engine",
	/* 0x34 */  "Unknown family code 0x34",
	/* 0x35 */  "Unknown family code 0x35",
	/* 0x36 */  "High precision coulomb counter",
	/* 0x37 */  "Password protected 32K EEPROM",
	/* 0x38 */  "Unknown family code 0x38",
	/* 0x39 */  "Unknown family code 0x39",
	/* 0x3a */  "Dual channel addressable switch",
	/* 0x3b */  "Unknown family code 0x3b",
	/* 0x3c */  "Unknown family code 0x3c",
	/* 0x3d */  "Unknown family code 0x3d",
	/* 0x3e */  "Unknown family code 0x3e",
	/* 0x3f */  "Unknown family code 0x3f",
	/* 0x40 */  "Unknown family code 0x40",
	/* 0x41 */  "Temperature logger with 8K memory",
	/* 0x42 */  "Unknown family code 0x42",
	/* 0x43 */  "Unknown family code 0x43",
	/* 0x44 */  "Unknown family code 0x44",
	/* 0x45 */  "Unknown family code 0x45",
	/* 0x46 */  "Unknown family code 0x46",
	/* 0x47 */  "Unknown family code 0x47",
	/* 0x48 */  "Unknown family code 0x48",
	/* 0x49 */  "Unknown family code 0x49",
	/* 0x4a */  "Unknown family code 0x4a",
	/* 0x4b */  "Unknown family code 0x4b",
	/* 0x4c */  "Unknown family code 0x4c",
	/* 0x4d */  "Unknown family code 0x4d",
	/* 0x4e */  "Unknown family code 0x4e",
	/* 0x4f */  "Unknown family code 0x4f",
	/* 0x50 */  "Unknown family code 0x50",
	/* 0x51 */  "Multi-chemistry battery fuel guage",
	/* 0x52 */  "Unknown family code 0x52",
	/* 0x53 */  "Unknown family code 0x53",
	/* 0x54 */  "Unknown family code 0x54",
	/* 0x55 */  "Unknown family code 0x55",
	/* 0x56 */  "Unknown family code 0x56",
	/* 0x57 */  "Unknown family code 0x57",
	/* 0x58 */  "Unknown family code 0x58",
	/* 0x59 */  "Unknown family code 0x59",
	/* 0x5a */  "Unknown family code 0x5a",
	/* 0x5b */  "Unknown family code 0x5b",
	/* 0x5c */  "Unknown family code 0x5c",
	/* 0x5d */  "Unknown family code 0x5d",
	/* 0x5e */  "Unknown family code 0x5e",
	/* 0x5f */  "Unknown family code 0x5f",
	/* 0x60 */  "Unknown family code 0x60",
	/* 0x61 */  "Unknown family code 0x61",
	/* 0x62 */  "Unknown family code 0x62",
	/* 0x63 */  "Unknown family code 0x63",
	/* 0x64 */  "Unknown family code 0x64",
	/* 0x65 */  "Unknown family code 0x65",
	/* 0x66 */  "Unknown family code 0x66",
	/* 0x67 */  "Unknown family code 0x67",
	/* 0x68 */  "Unknown family code 0x68",
	/* 0x69 */  "Unknown family code 0x69",
	/* 0x6a */  "Unknown family code 0x6a",
	/* 0x6b */  "Unknown family code 0x6b",
	/* 0x6c */  "Unknown family code 0x6c",
	/* 0x6d */  "Unknown family code 0x6d",
	/* 0x6e */  "Unknown family code 0x6e",
	/* 0x6f */  "Unknown family code 0x6f",
	/* 0x70 */  "Unknown family code 0x70",
	/* 0x71 */  "Unknown family code 0x71",
	/* 0x72 */  "Unknown family code 0x72",
	/* 0x73 */  "Unknown family code 0x73",
	/* 0x74 */  "Unknown family code 0x74",
	/* 0x75 */  "Unknown family code 0x75",
	/* 0x76 */  "Unknown family code 0x76",
	/* 0x77 */  "Unknown family code 0x77",
	/* 0x78 */  "Unknown family code 0x78",
	/* 0x79 */  "Unknown family code 0x79",
	/* 0x7a */  "Unknown family code 0x7a",
	/* 0x7b */  "Unknown family code 0x7b",
	/* 0x7c */  "Unknown family code 0x7c",
	/* 0x7d */  "Unknown family code 0x7d",
	/* 0x7e */  "Unknown family code 0x7e",
	/* 0x7f */  "Unknown family code 0x7f",
	/* 0x80 */  "Unknown family code 0x80",
	/* 0x81 */  "Unknown family code 0x81",
	/* 0x82 */  "Unknown family code 0x82",
	/* 0x83 */  "Unknown family code 0x83",
	/* 0x84 */  "Dual port plus time",
	/* 0x85 */  "Unknown family code 0x85",
	/* 0x86 */  "Unknown family code 0x86",
	/* 0x87 */  "Unknown family code 0x87",
	/* 0x88 */  "Unknown family code 0x88",
	/* 0x89 */  "48bit node address chip",
	/* 0x8a */  "Unknown family code 0x8a",
	/* 0x8b */  "16K add-only uniqueware",
	/* 0x8c */  "Unknown family code 0x8c",
	/* 0x8d */  "Unknown family code 0x8d",
	/* 0x8e */  "Unknown family code 0x8e",
	/* 0x8f */  "64K add-only uniqueware",
	/* 0x90 */  "Unknown family code 0x90",
	/* 0x91 */  "512 bit EEPROM memory",
	/* 0x92 */  "Unknown family code 0x92",
	/* 0x93 */  "Unknown family code 0x93",
	/* 0x94 */  "Unknown family code 0x94",
	/* 0x95 */  "Unknown family code 0x95",
	/* 0x96 */  "Java-powered cryptographic iButton (64K ROM, 6-134K NVRAM)",
	/* 0x97 */  "Unknown family code 0x97",
	/* 0x98 */  "Unknown family code 0x98",
	/* 0x99 */  "Unknown family code 0x99",
	/* 0x9a */  "Unknown family code 0x9a",
	/* 0x9b */  "Unknown family code 0x9b",
	/* 0x9c */  "Unknown family code 0x9c",
	/* 0x9d */  "Unknown family code 0x9d",
	/* 0x9e */  "Unknown family code 0x9e",
	/* 0x9f */  "Unknown family code 0x9f",
	/* 0xa0 */  "Unknown family code 0xa0",
	/* 0xa1 */  "Unknown family code 0xa1",
	/* 0xa2 */  "Unknown family code 0xa2",
	/* 0xa3 */  "Unknown family code 0xa3",
	/* 0xa4 */  "Unknown family code 0xa4",
	/* 0xa5 */  "Unknown family code 0xa5",
	/* 0xa6 */  "Unknown family code 0xa6",
	/* 0xa7 */  "Unknown family code 0xa7",
	/* 0xa8 */  "Unknown family code 0xa8",
	/* 0xa9 */  "Unknown family code 0xa9",
	/* 0xaa */  "Unknown family code 0xaa",
	/* 0xab */  "Unknown family code 0xab",
	/* 0xac */  "Unknown family code 0xac",
	/* 0xad */  "Unknown family code 0xad",
	/* 0xae */  "Unknown family code 0xae",
	/* 0xaf */  "Unknown family code 0xaf",
	/* 0xb0 */  "Unknown family code 0xb0",
	/* 0xb1 */  "Unknown family code 0xb1",
	/* 0xb2 */  "Unknown family code 0xb2",
	/* 0xb3 */  "Unknown family code 0xb3",
	/* 0xb4 */  "Unknown family code 0xb4",
	/* 0xb5 */  "Unknown family code 0xb5",
	/* 0xb6 */  "Unknown family code 0xb6",
	/* 0xb7 */  "Unknown family code 0xb7",
	/* 0xb8 */  "Unknown family code 0xb8",
	/* 0xb9 */  "Unknown family code 0xb9",
	/* 0xba */  "Unknown family code 0xba",
	/* 0xbb */  "Unknown family code 0xbb",
	/* 0xbc */  "Unknown family code 0xbc",
	/* 0xbd */  "Unknown family code 0xbd",
	/* 0xbe */  "Unknown family code 0xbe",
	/* 0xbf */  "Unknown family code 0xbf",
	/* 0xc0 */  "Unknown family code 0xc0",
	/* 0xc1 */  "Unknown family code 0xc1",
	/* 0xc2 */  "Unknown family code 0xc2",
	/* 0xc3 */  "Unknown family code 0xc3",
	/* 0xc4 */  "Unknown family code 0xc4",
	/* 0xc5 */  "Unknown family code 0xc5",
	/* 0xc6 */  "Unknown family code 0xc6",
	/* 0xc7 */  "Unknown family code 0xc7",
	/* 0xc8 */  "Unknown family code 0xc8",
	/* 0xc9 */  "Unknown family code 0xc9",
	/* 0xca */  "Unknown family code 0xca",
	/* 0xcb */  "Unknown family code 0xcb",
	/* 0xcc */  "Unknown family code 0xcc",
	/* 0xcd */  "Unknown family code 0xcd",
	/* 0xce */  "Unknown family code 0xce",
	/* 0xcf */  "Unknown family code 0xcf",
	/* 0xd0 */  "Unknown family code 0xd0",
	/* 0xd1 */  "Unknown family code 0xd1",
	/* 0xd2 */  "Unknown family code 0xd2",
	/* 0xd3 */  "Unknown family code 0xd3",
	/* 0xd4 */  "Unknown family code 0xd4",
	/* 0xd5 */  "Unknown family code 0xd5",
	/* 0xd6 */  "Unknown family code 0xd6",
	/* 0xd7 */  "Unknown family code 0xd7",
	/* 0xd8 */  "Unknown family code 0xd8",
	/* 0xd9 */  "Unknown family code 0xd9",
	/* 0xda */  "Unknown family code 0xda",
	/* 0xdb */  "Unknown family code 0xdb",
	/* 0xdc */  "Unknown family code 0xdc",
	/* 0xdd */  "Unknown family code 0xdd",
	/* 0xde */  "Unknown family code 0xde",
	/* 0xdf */  "Unknown family code 0xdf",
	/* 0xe0 */  "Unknown family code 0xe0",
	/* 0xe1 */  "Unknown family code 0xe1",
	/* 0xe2 */  "Unknown family code 0xe2",
	/* 0xe3 */  "Unknown family code 0xe3",
	/* 0xe4 */  "Unknown family code 0xe4",
	/* 0xe5 */  "Unknown family code 0xe5",
	/* 0xe6 */  "Unknown family code 0xe6",
	/* 0xe7 */  "Unknown family code 0xe7",
	/* 0xe8 */  "Unknown family code 0xe8",
	/* 0xe9 */  "Unknown family code 0xe9",
	/* 0xea */  "Unknown family code 0xea",
	/* 0xeb */  "Unknown family code 0xeb",
	/* 0xec */  "Unknown family code 0xec",
	/* 0xed */  "Unknown family code 0xed",
	/* 0xee */  "Unknown family code 0xee",
	/* 0xef */  "Unknown family code 0xef",
	/* 0xf0 */  "Unknown family code 0xf0",
	/* 0xf1 */  "Unknown family code 0xf1",
	/* 0xf2 */  "Unknown family code 0xf2",
	/* 0xf3 */  "Unknown family code 0xf3",
	/* 0xf4 */  "Unknown family code 0xf4",
	/* 0xf5 */  "Unknown family code 0xf5",
	/* 0xf6 */  "Unknown family code 0xf6",
	/* 0xf7 */  "Unknown family code 0xf7",
	/* 0xf8 */  "Unknown family code 0xf8",
	/* 0xf9 */  "Unknown family code 0xf9",
	/* 0xfa */  "Unknown family code 0xfa",
	/* 0xfb */  "Unknown family code 0xfb",
	/* 0xfc */  "Unknown family code 0xfc",
	/* 0xfd */  "Unknown family code 0xfd",
	/* 0xfe */  "Unknown family code 0xfe",
	/* 0xff */  "Unknown family code 0xff"
};

#if defined(__cplusplus)
}
#endif

#endif /* !defined(__OWIRE_DEVICES_PRIVATE_H__ */
